spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/malldb
        driverClassName: org.mariadb.jdbc.Driver
        username: admin
        password: 1234
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
            show-sql: true
server:
    port: 8080
