spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/malldb
        driverClassName: org.mariadb.jdbc.Driver
        username: admin
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true


server:
    port: 8080
#    servlet:
#        context-path: /api
