spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/malldb
        driverClassName: org.mariadb.jdbc.Driver
        username: admin
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    servlet:
        multipart:
            max-request-size: 60MB #한번에 전송 가능 데이터 크기
            max-file-size: 60MB #파일의 최대 크기

org:
    zerock:
        upload:
            path: upload

server:
    port: 8080
#    servlet:
#        context-path: /api
logging:
    level:
        org:
            springframework:
                security:
                    web: trace

